# Kitty terminal config — Nightlion V1
# https://sw.kovidgoyal.net/kitty/conf.html

font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

foreground            #BBBBBB
background            #000000
cursor                #BBBBBB
selection_foreground  #BBBBBB
selection_background  #555555

color0  #4C4C4C
color1  #BB0000
color2  #5FDE8F
color3  #F3F167
color4  #276BD8
color5  #BB00BB
color6  #00DADF
color7  #BBBBBB
color8  #555555
color9  #FF5555
color10 #55FF55
color11 #FFFF55
color12 #5555FF
color13 #FF55FF
color14 #55FFFF
color15 #FFFFFF

cursor_shape          block
cursor_blink_interval 0
mouse_hide_wait       2.0
window_padding_width  4
confirm_os_window_close 0

shell_integration     enabled
shell                 /usr/bin/zsh

enable_audio_bell     no
visual_bell_duration  0.0

tab_bar_style         powerline
tab_bar_edge          bottom
active_tab_foreground #000000
active_tab_background #00DADF
inactive_tab_foreground #BBBBBB
inactive_tab_background #333333

map ctrl+shift+t      new_tab
map ctrl+shift+q      close_tab
map ctrl+shift+enter  new_window
map ctrl+shift+w      close_window
map ctrl+shift+]      next_window
map ctrl+shift+[      previous_window
map ctrl+shift+left   previous_tab
map ctrl+shift+right  next_tab
map ctrl+shift+f      toggle_fullscreen
map ctrl+shift+r      load_config_file
map ctrl+shift+up     resize_window
map ctrl+shift+down   resize_window
