# ┌──────────────────────────────────────────────────────────────────┐
# │ Hypridle — Idle daemon                                            │
# └──────────────────────────────────────────────────────────────────┘

general {
    lock_cmd = hyprlock
    after_idle = 300  # 5 min
    after_suspend = 600  # 10 min
}

listener {
    timeout = 300
    on_idle = hyprctl dispatch dpms off
    on_resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on_idle = systemctl suspend
}
