# Generado por matugen — NO editar a mano
# Tema dinámico desde wallpaper (Material You)

general {
    col.active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.secondary.default.hex_stripped}}ff) rgba({{colors.tertiary.default.hex_stripped}}ff) 45deg
    col.inactive_border = rgba({{colors.surface_container_highest.default.hex_stripped}}ff)
}

decoration {
    shadow {
        color = rgba({{colors.surface_container_highest.default.hex_stripped}}66)
    }
}
