# ┌──────────────────────────────────────────────────────────────────┐
# │ btop theme — Catppuccin Mocha                                    │
# │ https://github.com/aristocratos/btop                              │
# └──────────────────────────────────────────────────────────────────┘

# Theme
color_theme = "phoenix-night"

# Flags
show_battery = "Auto"
show_cpu_temp = "C"
show_cpu_freq = "on"
show_network = "on"
show_disks = "on"
show_mem = "on"
show_swap = "on"
show_uptime = "on"
show_proc = "on"
show_proc_cpu = "on"
show_proc_mem = "on"
proc_sort = "cpu lazy"
proc_reversed = "False"
proc_per_core = "False"
proc_tree = "False"
proc_colors = "True"
proc_gradient = "True"
proc_mem_bytes = "False"
check_temp = "C"
cpu_sensor = "Auto"
show_coretemp = "on"
show_cpufreq = "on"
show_gputemp = "off"
show_gpu_mem = "off"
cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
mem_graph_upper = "Auto"
mem_graph_lower = "Auto"
net_graph_upper = "Auto"
net_graph_lower = "Auto"
divider = "Auto"
show_theme_help = "False"
update_ms = "1500"
log_level = "warn"
boxed = "Auto"

# Visual
graph_symbol = "braille"
background = "False"
theme_background = "False"
truecolor = "True"
lowcolor = "False"
mouse = "True"
rounded_corners = "True"
alias_logscale = "True"
show_clock = "True"
clock_format = "%H:%M"
clock_24hr = "auto"
locale = "C.UTF-8"
text_zoom = "1.0"
size_overhead = "True"
graph_data = "Normal"
graph_line = "Filled"
status_data = "Normal"
show_status = "True"
show_procs = "6"
proc_smoothing = "True"
proc_service_zoom = "1.5"
show_kern = "False"
show_vm = "False"
base_theme = "default"
